version: '3.4'

services:
  aeroflots:
    image: ${DOCKER_REGISTRY-}aeroflots
    build:
      context: .
      dockerfile: aeroflots/Dockerfile
    depends_on:
      - db
    ports:
      - "5080:5080"
  db:
    image: postgres